/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package piedrapapeltijera;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dekna
 */
public class Menu extends javax.swing.JFrame {
    PiedraPapelTijera pi;
    Juego ju;
    Menu me;
    Juego facil;
    boolean dificil;
    public int i =0;
    ArrayList<Integer> numerosPrevios = new ArrayList<Integer>();
   public int intentos1;
    /**
     * Creates new form Menu
     */
    public Menu() {
        this.dificil = true;
       
        initComponents();
    }
    public Menu (PiedraPapelTijera pip){
        this.dificil = true;
        setSize(400,400);
        initComponents();
        setLocationRelativeTo(null);
        pi = pip;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtintentos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piedrapapeltijera/fondo.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Piedra Papel Tijera");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 40, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 0, 51));
        jCheckBox1.setText("fácil");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 85, -1));

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 254, 103, 46));

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("¿Cuantos intentos quieres?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        txtintentos.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        txtintentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtintentosActionPerformed(evt);
            }
        });
        getContentPane().add(txtintentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 55, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piedrapapeltijera/fondo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 600, 310));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
      dificil=false;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       me = new Menu();
       me.setVisible(false);
       dispose();
         try {
         String text = txtintentos.getText();
         intentos1 = Integer.parseInt(text);
         if(intentos1>=9){
           intentos1 = 9;
         }if(intentos1<=0){
           intentos1 = 1;
         }
            
        if (jCheckBox1.isSelected()) {
            facil = new Juego( dificil=false);
            facil.setVisible(true);
            facil.initUI(intentos1);
        }else{
             ju = new Juego();
             ju.setVisible(true);
             ju.initUI(intentos1);
        }
        me = new Menu();
        me.setVisible(false);
        dispose();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "El valor introducido no es un número, intentalo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        ju.setVisible(false);
        dispose();
        me.setVisible(true);
         setSize(400,400);
         ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtintentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtintentosActionPerformed
        
    }//GEN-LAST:event_txtintentosActionPerformed
      
//    void record(){
//        if (ju.puntuacion > ju.puntuacion) {
//            ju.puntuacion.setText(ju.puntuacion + "");
//        }
//    }
    int numalt(int min, int max){
        int x = (int) ((Math.random()*((max-min)+1))+min);
        return x;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtintentos;
    // End of variables declaration//GEN-END:variables
}
